[project]
name = "llm-rl-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.4.7",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
