name: Run Pytest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ github.repository }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ github.repository }}-

      - name: Install `uv`
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install Dependencies using `uv sync`
        run: |
          uv sync

      - name: Download dataset files
        run: |
          uv run download_gsm8k.py

      - name: Run Pytest
        run: uv run pytest --tb=short --disable-warnings